package com.checkproof.explore.ai_tool_java_copilot.enumeration;

public enum Role {
  ADMIN, USER, GUEST, INSPECTOR, SAFETY_OFFICER, MANAGER, SUPERVISOR, ENGINEER, TECHNICIAN, OPERATOR, ANALYST, CONSULTANT, COORDINATOR, DIRECTOR, EXECUTIVE, INTERN, CONTRACTOR, PARTNER, STAKEHOLDER;
}
